### PR TITLE
Use pathlib for path manipulation

### PR DESCRIPTION
**Pull request by eumiro**
Although Python's `pathlib.Path` can't directly handle URLs, it can be used to manipulate their path part.

### CODE REVIEW

**Comment by jugmac00** [comment]
Thank you very much.

I cherry-picked the typo fix commit right away - let's see, whether I can delete the commit from the pull request myself.

About the `pathlib` commit, I have to think a bit. Actually, both the old and the new version are not super expressive about what is happening. I think adding a comment with an example URL (before and after) will clarify what is happening. I will do this myself, as I'd like to play with the debugger of VS Code.

Also, I really have to add some tests, see #4.

I certainly heard of `pathlib`, but as I still have to maintain a Python 2 code base, I have not used it much. Both `relative_to` and `with_suffix` were new to me.

Thanks for teaching me something new!

**Comment by eumiro** [comment]
Maybe have a look at [`urlpath`](https://pypi.org/project/urlpath/) that combines the function of `urllib.parse` and `pathlib` to get the right level of expressiveness.

**Review by eumiro — COMMENTED** [review]
Looks good to me.

**Comment by jugmac00** [comment]
Thanks for the hint about `urlpath` - the lib looks good, but I won't consider it for now for two reasons:
- the maintainer does not react to new issues, like deprecation warnings, so I fear the library won't work with future Python versions
- I will try to keep external dependencies at a minimum, as I either have to update them regularly or in the worst case, when they get unmaintained, I need to replace them

Speaking of external dependencies, maybe I could get rid of `httpx`, too, by replacing it with `urllib` from the standard library.

I refactored the new usage of `Path` a bit, and also added some inline comments how the URLs/paths look. I guess I need this verbose code as I am not super familiar with `pathlib` yet.

Thanks a lot for your input!

Now let's try to merge this...

**Pull request merged**
